### ISSUE TITLE
Dataspaces als aparte repository nog weghalen

### ISSUE THREAD

**Issue by wboersma** [Geonovum/eu_regelingen_datastrategie#13]
Ton, ik kwam er achter dat de repository rondom de dataspaces (dus wat je eerst had opgezet als aparte repository) ook nog bestaat. Omdat het nu een hoofdstuk (H10) is van de handreiking is het wel handig om de oude repository nog weg te halen (want wordt die nog wel geüpdatet of verwijs je naar dezelfde bronbestanden). Maar qua URL's lijkt het mij handig om die versie niet meer actief te houden.
Het betreft deze index volgens mij: [dsindex.html](https://github.com/Geonovum/eu_regelingen_datastrategie/blob/main/dsindex.html) (denk ik)

**Comment by tonzyl** [comment]
de geconsolideerde versie gebruikt dezelfde bronbestanden. Het gaat inderdaad om dsindex.html, daar linkt nu verder niets na (en dus 'bestaat het niet' in de github.io site in de zin dat je de url moet kennen om er te komen, en is hiet geen onderdeel van docs.geostandaarden.nl, want tijdens omzetting wordt dsindex.html niet meegenomen. Ik wil hem graag laten staan omdat ik vermoed dat we uiteindelijk toch wel te maken gaan krijgen met meerdere onderdelen.

**Comment by wboersma** [comment]
Ja ik kende de url en zo kwam ik er. Maar als dezelfde bronbestanden worden gebruikt dan gaat er niks mis. En fijn om te weten dat het geen onderdeel nu is van docs.geostandaarden.nl. Prima om hem te laten staan hoor. Ik denk namelijk ook dat we te maken krijgen met meerdere onderdelen...
