### ISSUE TITLE
Opmerkingen dataspaces inleiding en Green Deal dataspace

### ISSUE THREAD

**Issue by wboersma** [Geonovum/eu_regelingen_datastrategie#9]
Link naar de data strategie (EU-wiki) opgenomen.
Engelse teksten omgezet  NL teksten; met name tekstuele aanpassingen.

**Comment by wboersma** [comment]
Algemeen vind ik de dataspace-wiki meer opsomming gericht en NL- EN door elkaar. Zal ik de rest van de teksten met name tekstueel (punten, vergeten letters) aanpassen?

**Comment by tonzyl** [comment]
Ik ga even kijken hoe ik dit beter kan beschrijven/vormgeven ook t.a.v. de verbinding met de DEP calls.
